### ISSUE TITLE
Need to add include paths

### ISSUE THREAD

**Issue by burghto911** [nightrune/wrench#34]

**Comment by nightrune** [comment]
Yes this is definitely planned. The file build.go has these. I planned on having support for them in the settings.wrench file. I think you can see the early support for it in the "dirs" element. This needs to get plumbed through to build.go and then create the command line arguments for gpp from there.

**Comment by burghto911** [comment]
Thanks.  I figured this was on the road map but I saw that you had other
issues out there for future features so I thought I would log this one as
well.

-Todd Burghgraef
Watershed Technologies
Phone: (616) 318-7235
Email: burghto@watershed-tech.com

**Comment by nightrune** [comment]
@burghto911 This now has support for this. Have you attempted to build it yet?

**Comment by burghto911** [comment]
Do you have an easy way to build wrench to include the new updates?

-Todd Burghgraef
Watershed Technologies
Phone: (616) 318-7235
Email: burghto@watershed-tech.com

**Comment by nightrune** [comment]
I do yeah. Should I just build and send a copy on an update?
