### ISSUE TITLE
can't comment out #include lines

### ISSUE THREAD

**Issue by burghto911** [nightrune/wrench#35]
the following line still includes a file:

//#include "myfile.nut"

**Comment by nightrune** [comment]
This is a problem with gpp. We aren't likely to fix that anytime soon. I've noticed it does this with lines like `#endif  // package name` as well.

**Comment by nightrune** [comment]
@burghto911 I can't reproduce this.

**Comment by nightrune** [comment]
Fixed with latest issue. Specificially the we used the -C command in gpp.
